services:
  backend-prod:
    image: backend-prod
    build:
      context: ./shopping-backend
      dockerfile: Dockerfile
  frontend-prod:
    image: frontend-prod
    build:
      context: ./shoppingcart
      dockerfile: Dockerfile
    environment:
      REACT_APP_BACKEND: http://localhost:8080/api/products
    depends_on:
      - backend-prod
  nginx:
    image: nginx:1.29
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - backend-prod
      - frontend-prod